### ISSUE TITLE
Final UI checklist & cleanup

### ISSUE THREAD

**Issue by dfilaretti** [dfilaretti/uplift-arpeggio#19]
- [ ] check we are using Ableton Sans
- [ ] check that sizes and positions are integer numbers (in the inspector)
- [ ] check there isn't output in the console
- [ ] make sure LED mode is enabled when possible
- [ ] check help texts
